// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  publisher.models.Profile = (function(_super) {

    __extends(Profile, _super);

    function Profile() {
      return Profile.__super__.constructor.apply(this, arguments);
    }

    Profile.prototype.defaults = {
      id: ""
    };

    Profile.prototype.url = function() {
      return "/api/1.0/account/profile/?format=json";
    };

    return Profile;

  })(Backbone.Model);

  publisher.app.data.profile = new publisher.models.Profile();

}).call(this);
